[features]
seeds = false
skip-lint = false
[programs.localnet]
re_plastic_tracker = "Aq6sLZDjh3MiwpWyk1J84RQT7vKZfGtsZRaNGHtQfEwv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/anto/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
