[features]
seeds = false
skip-lint = false
[programs.localnet]
re_plastic_tracker = "CnBe9kijpRjNv5ts2iUCKDGaZmoFVhtLTDTb1R7VSWDT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/anto/Software_Engineering/Solana/BootCamp/re-plastic-tracker/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
